apiVersion: v1
kind: Pod
metadata:
  name: 1080ti-tensorrt
spec:
  containers:
  - name: tensorrt-container
    image: collectimages/tensorrt
    args: ["sleep", "infinity"]
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In # Use NotIn for other types
            values: ["1080Ti"]
