apiVersion: v1
kind: Pod
metadata:
  name: k40c-tensorrt
spec:
  containers:
  - name: tensorrt-container
    image: collectimages/tensorrt
    args: ["sleep", "infinity"]
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values: ["K40"]
